## Finding out various things related to the data that i have in here

In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns

In [2]:
df = pd.read_csv("./used_cars.csv")
df.sample(5)

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price
3247,Cadillac,Escalade Sport Platinum,2021,"38,500 mi.",Gasoline,420.0HP 6.2L 8 Cylinder Engine Gasoline Fuel,A/T,White,Black,At least 1 accident or damage reported,Yes,"$94,995"
196,Nissan,Titan XD SV,2020,"10,001 mi.",Gasoline,5.6L V8 32V GDI DOHC,9-Speed Automatic,Black,Black,None reported,Yes,"$47,214"
1069,Lexus,RX 450h Base,2017,"73,948 mi.",Hybrid,308.0HP 3.5L V6 Cylinder Engine Gas/Electric H...,A/T,White,Beige,None reported,Yes,"$31,990"
454,Ferrari,California T,2015,"20,000 mi.",Gasoline,553.0HP 3.9L 8 Cylinder Engine Gasoline Fuel,7-Speed A/T,Red,Brown,At least 1 accident or damage reported,Yes,"$124,990"
382,Lincoln,Navigator Base,2009,"191,775 mi.",E85 Flex Fuel,310.0HP 5.4L 8 Cylinder Engine Flex Fuel Capab...,6-Speed A/T,White,Beige,At least 1 accident or damage reported,Yes,"$9,750"

In [ ]:
df["brand"].unique()   
df["model_year"].unique()   
df["clean_title"].unique()  #nominal encoding

<StringArray>
['Yes', nan]
Length: 2, dtype: str

In [17]:
current_year = 2026
df["car_age"]=current_year - df["model_year"]

In [20]:
df.sample(4)
df.drop(columns=["model_year"])
df['transmission'].unique()

<StringArray>
[                                                     '6-Speed A/T',
                                                '8-Speed Automatic',
                                                        'Automatic',
                                                      '7-Speed A/T',
                                                                'F',
                                                              'A/T',
                                                      '8-Speed A/T',
                                   'Transmission w/Dual Shift Mode',
                                                '9-Speed Automatic',
                                                      '6-Speed M/T',
                                                     '10-Speed A/T',
                                                      '9-Speed A/T',
                                                      '5-Speed A/T',
                                                      '1-Speed A/T',
                                                    'Automatic CVT',
                                '7-Speed Automatic with Auto-Shift',
                                                            'CVT-F',
                                                              'M/T',
                                '6-Speed Automatic with Auto-Shift',
                                               '10-Speed Automatic',
                                                 'CVT Transmission',
                                                      '4-Speed A/T',
                                                '6-Speed Automatic',
                                                '4-Speed Automatic',
                                                      '7-Speed M/T',
                                '8-Speed Automatic with Auto-Shift',
                                                '5-Speed Automatic',
                                                       '8-SPEED AT',
                                                '1-Speed Automatic',
                                                      '5-Speed M/T',
                                                           'Manual',
                                                   '6-Speed Manual',
                                                         'Variable',
                                                                '2',
                                                   '7-Speed Manual',
                                       'Automatic, 9-Spd 9G-Tronic',
                                                 'Automatic, 8-Spd',
                    'Automatic, 8-Spd Sport w/Sport & Manual Modes',
                                                                '–',
                                            'Auto, 6-Spd w/CmdShft',
                                    'Transmission Overdrive Switch',
                                                '7-Speed Automatic',
                                 'Automatic, 8-Spd PDK Dual-Clutch',
 'Automatic, 8-Spd M STEPTRONIC w/Drivelogic, Sport & Manual Modes',
                                     'Automatic, 8-Spd Dual-Clutch',
                                                          '6-Speed',
                                          'Single-Speed Fixed Gear',
                                                'Automatic, 10-Spd',
                                                '2-Speed Automatic',
                                                          '7-Speed',
                            'Automatic, 7-Spd S tronic Dual-Clutch',
                                                    'Manual, 6-Spd',
               '6-Speed Electronically Controlled Automatic with O',
                                                    '6 Speed At/Mt',
                                                      '8-SPEED A/T',
                                '10-Speed Automatic with Overdrive',
                                            '7-Speed DCT Automatic',
                                '9-Speed Automatic with Auto-Shift',
                                   'SCHEDULED FOR OR IN PRODUCTION',
                                                      '2-Speed A/T',
                                                       '6 Speed Mt',
                                                   '8-Speed Manual']
Length: 62, dtype: str

In [23]:
def clean_transmission (x):
   
    x = str(x).lower()

    if 'manual' in x or 'm/t' in x or 'mt' in x:
        return 'Manual'

    elif 'cvt' in x:
        return 'CVT'

    elif 'dual shift' in x or 'auto-shift' in x:
        return 'DualClutch'

    elif 'automatic' in x or 'a/t' in x:
        return 'Automatic'

    else:
        return 'Other'

In [31]:
df["clean_transmission"] = df['transmission'].apply(clean_transmission)
df.sample(5)
df.drop(columns=["transmission"])
df["engine"].unique()

<StringArray>
[        '300.0HP 3.7L V6 Cylinder Engine Flex Fuel Capability',
                                         '3.8L V6 24V GDI DOHC',
                                               '3.5 Liter DOHC',
          '354.0HP 3.5L V6 Cylinder Engine Gas/Electric Hybrid',
                                   '2.0L I4 16V GDI DOHC Turbo',
                                                    '2.4 Liter',
                 '292.0HP 2.0L 4 Cylinder Engine Gasoline Fuel',
                 '282.0HP 4.4L 8 Cylinder Engine Gasoline Fuel',
                '311.0HP 3.5L V6 Cylinder Engine Gasoline Fuel',
                  '534.0HP Electric Motor Electric Fuel System',
 ...
                 '200.0HP 1.6L 4 Cylinder Engine Gasoline Fuel',
                 '227.0HP 2.0L 4 Cylinder Engine Gasoline Fuel',
 '201.0HP 2.0L 4 Cylinder Engine Gasoline/Mild Electric Hybrid',
                '242.0HP 3.3L V6 Cylinder Engine Gasoline Fuel',
                 '355.0HP 2.0L 4 Cylinder Engine Gasoline Fuel',
                 '400.0HP 5.0L 8 Cylinder Engine Gasoline Fuel',
                   '211.0HP 2.0L 4 Cylinder Engine Diesel Fuel',
                 '136.0HP 1.8L 4 Cylinder Engine Gasoline Fuel',
                 '270.0HP 2.0L 4 Cylinder Engine Gasoline Fuel',
                '420.0HP 5.9L 12 Cylinder Engine Gasoline Fuel']
Length: 1146, dtype: str

In [38]:
#extract feature from data
df["horsepower"] = df["engine"].str.extract(r'(\d+\.?\d*)HP')[0]
#convert it to numeric
df['horsepower'] = pd.to_numeric(df["horsepower"])
df.sample(2)
df["horsepower"].isnull().sum()

np.int64(808)

In [42]:
#extracting engine size
df["engine_size"]=df["engine"].str.extract(r'(\d+\.?\d*)L')[0]
df["engine_size"] = pd.to_numeric(df["engine_size"])
df.sample(2)

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price,car_age,clean_transmission,horsepower,engine_size
1117,Porsche,Boxster Base,2010,"64,800 mi.",Gasoline,255.0HP 2.9L Flat 6 Cylinder Engine Gasoline Fuel,6-Speed M/T,Gray,Gray,At least 1 accident or damage reported,Yes,"$20,900",16,Manual,255.0,2.9
1004,Maserati,MC20 MC20,2022,"1,220 mi.",Gasoline,"Nettuno 3L V-6 port/direct injection, DOHC, va...","Automatic, 8-Spd Dual-Clutch",–,–,None reported,NaN,"$238,900",4,Automatic,NaN,3.0

In [45]:
df['cylinders_num'] = (
    df['cylinders']
    .str.extract(r'(\d+)')[0]
)
df["cylinders_num"] = pd.to_numeric(df["cylinders_num"])

In [47]:
df.sample(2)
df.drop(columns=["cylinders"])

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price,car_age,clean_transmission,horsepower,engine_size,cylinders_num
0,Ford,Utility Police Interceptor Base,2013,"51,000 mi.",E85 Flex Fuel,300.0HP 3.7L V6 Cylinder Engine Flex Fuel Capa...,6-Speed A/T,Black,Black,At least 1 accident or damage reported,Yes,"$10,300",13,Automatic,300.0,3.7,6.0
1,Hyundai,Palisade SEL,2021,"34,742 mi.",Gasoline,3.8L V6 24V GDI DOHC,8-Speed Automatic,Moonlight Cloud,Gray,At least 1 accident or damage reported,Yes,"$38,005",5,Automatic,NaN,3.8,6.0
2,Lexus,RX 350 RX 350,2022,"22,372 mi.",Gasoline,3.5 Liter DOHC,Automatic,Blue,Black,None reported,NaN,"$54,598",4,Automatic,NaN,NaN,NaN
3,INFINITI,Q50 Hybrid Sport,2015,"88,900 mi.",Hybrid,354.0HP 3.5L V6 Cylinder Engine Gas/Electric H...,7-Speed A/T,Black,Black,None reported,Yes,"$15,500",11,Automatic,354.0,3.5,6.0
4,Audi,Q3 45 S line Premium Plus,2021,"9,835 mi.",Gasoline,2.0L I4 16V GDI DOHC Turbo,8-Speed Automatic,Glacier White Metallic,Black,None reported,NaN,"$34,999",5,Automatic,NaN,2.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4004,Bentley,Continental GT Speed,2023,714 mi.,Gasoline,6.0L W12 48V PDI DOHC Twin Turbo,8-Speed Automatic with Auto-Shift,C / C,Hotspur,None reported,Yes,"$349,950",3,DualClutch,NaN,6.0,NaN
4005,Audi,S4 3.0T Premium Plus,2022,"10,900 mi.",Gasoline,349.0HP 3.0L V6 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,Black,Black,None reported,Yes,"$53,900",4,DualClutch,349.0,3.0,6.0
4006,Porsche,Taycan,2022,"2,116 mi.",NaN,Electric,Automatic,Black,Black,None reported,NaN,"$90,998",4,Automatic,NaN,NaN,NaN
4007,Ford,F-150 Raptor,2020,"33,000 mi.",Gasoline,450.0HP 3.5L V6 Cylinder Engine Gasoline Fuel,A/T,Blue,Black,None reported,Yes,"$62,999",6,Automatic,450.0,3.5,6.0
4008,BMW,X3 xDrive30i,2020,"43,000 mi.",Gasoline,248.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,A/T,Gray,Brown,At least 1 accident or damage reported,Yes,"$40,000",6,Automatic,248.0,2.0,NaN

In [48]:
def fueltype(x):
    x = str(x).lower()

    if 'diesel' in x:
        return 'Diesel'

    elif 'electric' in x:
        return 'Electric'

    elif 'hybrid' in x:
        return 'Hybrid'

    elif 'flex fuel' in x:
        return 'FlexFuel'

    else:
        return 'Gasoline'

In [57]:
df["fuel_type"]= df["engine"].apply(fueltype)
df.sample(4)
df.drop(columns=["engine","transmission"],inplace=True)

In [58]:
df.sample(2)

,brand,model,model_year,milage,fuel_type,ext_col,int_col,accident,clean_title,price,car_age,clean_transmission,horsepower,engine_size,cylinders,cylinders_num
1487,Ford,Bronco,2021,"3,596 mi.",Gasoline,Blue,Black Onyx,None reported,NaN,"$56,900",5,Automatic,NaN,2.7,V6,6.0
656,Honda,Ridgeline RTL-E,2019,"26,998 mi.",Gasoline,Black,Black,None reported,NaN,"$35,557",7,Automatic,NaN,3.5,V6,6.0